### ISSUE TITLE
Bowser crashes in Next.js Middleware Functions

### ISSUE THREAD

**Issue by voronianski** [bowser-js/bowser#512]
While trying to use Bowser inside [`_middleware` Next.js Middleware Functions](https://nextjs.org/docs/advanced-features/middleware) (also Vercel doc - https://vercel.com/docs/concepts/functions/edge-functions/middleware)

`req.headers.get('user-agent')` of the browser is: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`

However the exception is thrown - 
```bash
error - (middleware)/node_modules/bowser/src/parser.js (95:0) @ eval
Error: Browser's test function is not valid
```

You can use official Vercel example to try it yourself - https://github.com/vercel/examples/blob/main/edge-functions/user-agent-based-rendering/pages/_middleware.ts

**Comment by bingoYB** [comment]
I'm having the same problem, so when can this PR be merged.
